name: CI
on: [push]
jobs:
  eslint:
    name: Lint code base
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Run ESlint
        run: npm run lint

      - name: Start the app
        run: npm rub dev
