name: CI
on: [push]
jobs:
  eslint:
    name: Lint code base
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Install packages for client
        run: |
          cd client
          npm ci

      - name: Install packages for server
        run: |
          cd server
          npm ci

      - name: Run ESLint
        run: |
          cd client
          npm run lint

      - name: Start the app
        run: npm run dev
