name: CI
on: [push]
jobs:
  eslint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  

      - name: Install packages for client
        run: |
          cd client
          if [ -d "node_modules" ]; then rm -rf node_modules; fi
          if [ -f "package-lock.json" ]; then rm package-lock.json; fi
          npm install
          npm ci

      - name: Install packages for server
        run: |
          cd server
          if [ -d "node_modules" ]; then rm -rf node_modules; fi
          if [ -f "package-lock.json" ]; then rm package-lock.json; fi
          npm install
          npm ci

      - name: Run ESLint
        run: |
          cd client
          npm run lint